### ISSUE TITLE
catching also json-end-of-file for xmobar's benefit

### ISSUE THREAD

**Issue by jaor** [Stebalien/i3bar.el#1]
hi,

i was experimenting using i3bar.el with xmobar, which has a  flag to output JSON using swaybar's protocol (which is essentially i3bar's).  parsing of pango fonts is needed, but, before that, i've noticed that parsing of the output JSON needs to catch not only json-parse-error errors, but also json-end-of-file errors.  in other words, [this line](https://github.com/Stebalien/i3bar.el/blob/1cc9c7c198982fc31f25274c55cde80948720a7f/i3bar.el#L179) should read (i think):

```elisp
((json-parse-error json-end-of-file))
```
i'm not sure if that error can ever happen with i3status, but perhaps preventing it anyway won't hurt.

as an aside, in xmobar's case, one can ask for output in plain text lines, optionally coloured using ANSI escapes (using "xmobar -T").  that'd be almost trivial to support by i3bar.el (no parsing needed, just grab every line, pass it through `ansi-color-apply` or `ansi-color-apply-to-region` and set `i3bar-string` to the result)... not sure if you'd consider supporting such a "text-output-mode" (maybe with a customizable flag) out of scope for i3bar.el, just floating the idea :)

thanks!

**Comment by Stebalien** [comment]
> as an aside, in xmobar's case, one can ask for output in plain text lines, optionally coloured using ANSI escapes (using "xmobar -T"). that'd be almost trivial to support by i3bar.el (no parsing needed, just grab every line, pass it through ansi-color-apply or ansi-color-apply-to-region and set i3bar-string to the result)... not sure if you'd consider supporting such a "text-output-mode" (maybe with a customizable flag) out of scope for i3bar.el, just floating the idea :)

That seems reasonable. I'd probably implement it as some form of filter-function hook.

1. Could you file a new issue for that?
2. Does xmobar set the `markup` field to "ansi" in each text block? If so, I can implement this as a native feature.

**Comment by jaor** [comment]
On Mon, Aug 08 2022, Steven Allen wrote:

>  1. Could you file a new issue for that?

done

>  2. Does xmobar set the markup field to "ansi" in each text block? If
>  so, I can implement this as a native feature.

in ANSI mode, xmobar outputs directly the full formatted status string,
in a single line.  there is no markup to parse or anything, just ansi
escape sequences.  so no blocks either.  just take every line output by
xmobar, process its ansi escapes, and then assign the result to
i3bar-string should be enough.


thanks!
