### ISSUE TITLE
Cannot use this in EXWM

### ISSUE THREAD

**Issue by LemonBreezes** [Stebalien/i3bar.el#9]
Hi. For some reason, this package does not work on EXWM. It seems to expect the output of i3status to be JSON when it's just a string like "STRING1 | STRING2 | STRING3 | ...".

**Comment by Stebalien** [comment]
i3bar expects json output per https://i3wm.org/docs/i3bar-protocol.html, but I've only tested this package with i3status-rust. With i3status, it looks like you need to specify an `output_format` in the `general` section (https://i3wm.org/docs/i3status.html#_general)

Specifically:

```
general {
    output_format = "i3bar"
}
```

Once you get this working, I'd appreciate a patch to the readme with your findings if you have the time.
